import Head from 'next/head';
import TopicList from '../components/Topics/TopicList';
import getData from '@/utils/getData';
import { Raleway } from 'next/font/google';
import type { Topic } from '@/types/content-types';
import type { InferGetStaticPropsType } from 'next';

const releway = Raleway({ weight: ['600'], subsets: ['latin', 'cyrillic'] });

export default function Home(props: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='description'>
        <h2 className={releway.className}>{props.general.siteDescription}</h2>
      </div>
        <TopicList topics={props.topics} />
    </>
  );
}

export async function getStaticProps() {
  const data = await getData<{topics: Topic[]}>('/topics?status=active');

  return {
    props: {
      topics: data.topics || null,
      general: {
        siteName: 'Vethealth',
        siteDescription: 'Лікування та догляд за тваринами',
      },
    },
    revalidate: 1000,
  };
}
