import Head from 'next/head';
import Image from 'next/image';
import TopicList from '../components/Topics/TopicList';
import getData from '@/utils/getData';
import { Raleway } from 'next/font/google';
const releway = Raleway({ weight: ['600'], subsets: ['latin', 'cyrillic'] });

import styles from '../styles/Home.module.css';

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='description'>
        <h2 className={releway.className}>{props.general.siteDescription}</h2>
      </div>

      <section className="topics">
        <TopicList topics={props.topics} />
      </section>
    </>
  );
}

export async function getStaticProps() {
  const [data] = await Promise.all([
    getData('/topics'),
  ]);

  return {
    props: {
      topics: data.topics || null,
      general: {
        siteName: 'Vethealth',
        siteDescription: 'Лікування та догляд за тваринами',
      },
    },
    revalidate: 1000,
  };
}
