import type { Metadata } from 'next';
import Header from './components/Header';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-[#ebf6f7] min-h-screen">
      <Header />
      <main>
        <div className="container">{children}</div>
      </main>
    </div>
  );
}
